// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yafsezksblnhmkomtuud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZnNlemtzYmxuaG1rb210dXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwOTUzMjksImV4cCI6MjA1MjY3MTMyOX0.zHgW_2_wPZfYmPV-UxsqbV1BBaG3ewDcCxmgP741KbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);